# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-08 20:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stack', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='categories',
            field=models.ManyToManyField(to='stack.Tag'),
        ),
    ]
