# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-09 21:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stack', '0002_question_categories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='categories',
            new_name='tags',
        ),
    ]
